### ISSUE TITLE
Do we need `scoring_rule` argument?

### ISSUE THREAD

**Issue by mkim425** [mkim425/modelimportance#22]
There is currently a one-to-one mapping between `output_type` and the corresponding `scoring_rule`:

**Output Type | Scoring Rule**
-- | --
median | ae_point
mean | se_point
quantile | wis
pmf | log_score

Do we need `scoring_rule` as an argument in the function? 
https://github.com/mkim425/modelimportance/blob/1ff5814b978a5fe67a6e76f5cd07c46cc33f99bf/R/model_importance.R#L106C1-L109C1

I was wondering if we anticipate that future use cases could introduce additional scoring rules for each `output_type`. If so, having `scoring_rule` as an argument could provide the flexibility to accommodate these extensions, but otherwise, including it would seem redundant.

**Comment by nickreich** [comment]
I guess I'd vote for not including the `scoring_rule` argument for now, and if needed it could be added later without too much trouble.
